workflows:
  android-workflow:
    name: Hunter Radar APK Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Create Android folder if missing
        script: | 
          if [ ! -d "android" ]; then
            flutter create . --platforms android
          fi
      - name: Clean and Get dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - abdulmutiaseri290@gmail.com
