workflows:
  android-workflow:
    name: Hunter Radar APK Build
    working_directory: hunter_radar
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-codesign
    artifacts:
      - hunter_radar/build/app/outputs/flutter-apk/*.apk
